In [1]:
from pandas import read_csv
from matplotlib import pyplot
import sys
import numpy as np
import pandas as pd


import random

random.seed(10)

N=9
nowcast=1

tnoise=0.25

y_input_size=1
z_input_size=1


file="india_segmented.csv"
file="univer_segmented.csv"
file="solartech_segmented.csv"

series=read_csv(file, sep=",", header=0,parse_dates=True)
series=series.values
series


array([[0, '2017-06-13 00:00:00', 0.0, 24.851, 0.0],
       [1, '2017-06-13 00:10:00', 0.0, 24.802, 0.0],
       [2, '2017-06-13 00:20:00', 0.0, 24.758, 0.0],
       ...,
       [17133, '2017-11-21 23:30:00', 0.0, 7.949, 0.0],
       [17134, '2017-11-21 23:40:00', 0.0, 7.861, 0.0],
       [17135, '2017-11-21 23:50:00', 0.0, 7.681, 0.0]], dtype=object)

In [2]:

X1=sensors=np.array(series[:,2])
X2=sensors=np.array(series[:,3])
Y0=sensors=np.array(series[:,4])

print(X1[0])
print(X2[0])
print(Y0[0])

0.0
24.851
0.0


In [3]:
import tensorflow as tf 

X1n=tf.keras.utils.normalize(    X1, axis=-1, order=2)
X1n=np.array(X1n[0])
#X1n=X1


print(X1n)
print(X1n.shape)

X2n=tf.keras.utils.normalize(X2, axis=-1, order=2)
X2n=np.array(X2n[0])
#X2n=X2
print(X2n)
print(X2n.shape)

X0=np.zeros((len(X1n),2))

X0[:,0]=X1n
X0[:,1]=X2n

Y=np.zeros((len(Y0),1))
Y[:,0]=Y0

print(X0)
print(X0.shape)
print(Y.shape)
print(Y)

[0.0 0.0 0.0 ... 0.0 0.0 0.0]
(17136,)
[0.008708218143262458 0.008691047699858978 0.00867562934251708 ...
 0.002785466420699098 0.0027546297060152985 0.0026915546077984362]
(17136,)
[[0.         0.00870822]
 [0.         0.00869105]
 [0.         0.00867563]
 ...
 [0.         0.00278547]
 [0.         0.00275463]
 [0.         0.00269155]]
(17136, 2)
(17136, 1)
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [4]:
X=[]
for i in range(N,len(X0)):
    X.append(X0[i-N:i])
X=np.array(X)    
print(X.shape)

Y=Y[N-nowcast:len(Y)-nowcast]
print(Y.shape)



from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
print(Y[40])
scaler.fit(Y)

Y = scaler.transform(Y)
print(Y[40])

(17127, 9, 2)
(17127, 1)
[98.72755432]
[0.40682649]


In [5]:
print(X[0])
print(Y[0])

[[0.         0.00870822]
 [0.         0.00869105]
 [0.         0.00867563]
 [0.         0.00867878]
 [0.         0.008649  ]
 [0.         0.00857646]
 [0.         0.00851269]
 [0.         0.00850287]
 [0.         0.00851304]]
[0.]


In [6]:
from sklearn.model_selection import train_test_split
x_train , x_val , y_train , y_val = train_test_split(X , Y ,test_size=0.2, random_state=0)

In [7]:
from tensorflow import keras

from tensorflow.keras import layers
from keras.optimizers import Adam
from keras.layers import MaxPooling2D,Activation, Dense

from tensorflow import Tensor
from tensorflow.keras.layers import Input, Conv1D, Conv2D, ReLU, BatchNormalization,\
                                    Add, AveragePooling2D, Flatten, Dense,Dropout,LSTM,TimeDistributed,MaxPooling1D, concatenate
from tensorflow.keras.models import Model, Sequential

from keras import backend as K


mae = tf.keras.losses.MeanAbsoluteError()


def make_generator():
    x = Input(shape=(N,2))    
    x_output = Conv1D(filters=16, kernel_size=2, activation='relu')(x)
    x_output = Conv1D(filters=32, kernel_size=3, activation='relu')(x_output)
    x_output = Conv1D(filters=64, kernel_size=3, activation='relu')(x_output)
    x_output = Dropout(0.25)(x_output)
    x_output = LSTM(32, return_sequences=True)(x_output)
    x_output = Dropout(0.25)(x_output)
    x_output = LSTM(32)(x_output)
    latent = Flatten()(x_output)

    noise = Input(shape=(z_input_size,))
    noise_output = Dense(128, activation='relu')(noise)
    noise_output = Dense(64, activation='relu')(noise_output)
    
    flatten = concatenate([latent, noise_output])

    
    concat = Dense(256)(flatten)
    concat = Dense(128)(concat)
    y_fake = Dense(1,activation="sigmoid")(concat)

    model = Model(inputs=[x,noise], outputs=y_fake)
    return model  






def make_discriminator():
    
    x = Input(shape=(N,2))    
    x_output = Conv1D(filters=16, kernel_size=2, activation='relu')(x)
    x_output = Conv1D(filters=32, kernel_size=3, activation='relu')(x_output)
    x_output = Conv1D(filters=64, kernel_size=3, activation='relu')(x_output)
    x_output = Dropout(0.25)(x_output)
    x_output = LSTM(32, return_sequences=True)(x_output)
    x_output = Dropout(0.25)(x_output)
    x_output = LSTM(32)(x_output)
    latent = Flatten()(x_output)

    label = Input(shape=(y_input_size,))
    label_output = Dense(128, activation='relu')(label)
    label_output = Dense(64, activation='relu')(label_output)

    concat = concatenate([latent, label_output])
    concat = Dense(256)(concat)
    concat = Dense(128)(concat)
    validity = Dense(1,activation="sigmoid")(concat)

    model = Model(inputs=[x, label], outputs=validity)
    model.compile(loss=['binary_crossentropy'],optimizer='adam')
    model.summary()
    return model  

x = Input(shape=(N,2))
noise = Input(shape=(z_input_size,))
generator = make_generator()
label_fake = generator([x,noise])


discriminator = make_discriminator()

validity = discriminator([x, label_fake])

discriminator.trainable = False

combined = Model([noise, x], [label_fake,validity])
combined.compile(loss=['binary_crossentropy'],optimizer='adam',metrics=['accuracy'])
#combined.compile(loss=loss_error_gan,optimizer='adam')
combined.summary()

#combined = Sequential()
#combined.add(generator)
#combined.add(lier)
#combined.add(discriminator)
#combined.compile(loss='binary_crossentropy', optimizer='adam')
    


Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_5 (InputLayer)           [(None, 9, 2)]       0           []                               
                                                                                                  
 conv1d_3 (Conv1D)              (None, 8, 16)        80          ['input_5[0][0]']                
                                                                                                  
 conv1d_4 (Conv1D)              (None, 6, 32)        1568        ['conv1d_3[0][0]']               
                                                                                                  
 conv1d_5 (Conv1D)              (None, 4, 64)        6208        ['conv1d_4[0][0]']               
                                                                                            

In [8]:
print(x_train.shape)
print(y_train.shape)



#history = generator.fit(x_train,y_train ,
#                    batch_size=64,
#            validation_data=(x_val,y_val),
#            epochs=40)

(13701, 9, 2)
(13701, 1)


In [9]:
#from sklearn.metrics import confusion_matrix
#yhat = generator.predict(x_val)
#yhat=scaler.inverse_transform(yhat).flatten()
#y_val0=scaler.inverse_transform(y_val).flatten()
#print(y_val)
#print(yhat)

#file = open('prediction.csv', 'w')
#file.write('ground truth\tprediction\n')
#for i in range(0,len(y_val)):
#    file.write(str(y_val0[i])+"\t"+str(yhat[i])+"\n")
#file.close()

#print("RMSE")
#error=tf.keras.metrics.mean_squared_error(
#    y_val0, yhat
#)
#print(np.sqrt(error))

In [10]:
def generate_true_samples(batch_size):
    idx = np.random.randint(0, x_train.shape[0], batch_size)
    x, true_labels = x_train[idx], y_train[idx]
    return x,true_labels

def getNoise():
    return  np.random.uniform(-tnoise, tnoise, (batch_size, z_input_size))



In [11]:
import tensorflow as tf
tf.get_logger().setLevel('ERROR')

    
n_epochs=60
batch_size=64

valid = np.ones((batch_size, 1))
fake = np.zeros((batch_size, 1))


file = open('metrics_cgan0.csv', 'w')

for epoch in range(n_epochs):
    print("e:",epoch)
    for batch_idx in range(int(x_train.shape[0] // batch_size)):
        
        
        noise = getNoise()
        x,true_labels = generate_true_samples(batch_size)
        fake_labels = generator.predict([x,noise])

        discriminator.train_on_batch([x, true_labels], valid)
        discriminator.train_on_batch([x, fake_labels+noise], fake)
        discriminator.train_on_batch([x, fake_labels], valid)
        discriminator.train_on_batch([x, true_labels+noise], fake)
        
        x,true_labels = generate_true_samples(batch_size)
        fake_labels = generator.predict([x,noise])
        
        combined.train_on_batch([fake,x], [true_labels,fake])
        combined.train_on_batch([noise,x], [true_labels+noise,valid])
        combined.train_on_batch([fake_labels-true_labels,x], [fake_labels,valid])
        

    print(epoch, " of ", n_epochs)
    
    
    noise = np.zeros((x_val.shape[0], z_input_size))
    yhat = generator.predict([x_val,noise])
   
    yhat0=scaler.inverse_transform(yhat).flatten()
    y_val0=scaler.inverse_transform(y_val).flatten()

    error=tf.keras.metrics.mean_squared_error(
        y_val0, yhat0
    )
    print("error0",np.sqrt(error))    
    file.write(str(np.sqrt(error))+'\t')
    file.write(str(np.sqrt(tf.keras.metrics.mean_squared_error(
        y_val.flatten(), yhat.flatten()
    )))+'\t')
    
    pred_true=discriminator.predict([x_val, y_val])
    print(pred_true[pred_true>0.5])
    acc_true=len(pred_true[pred_true>=0.5])/len(y_val)   
    print("pred_true:",pred_true,acc_true)
    file.write(str(acc_true)+'\t')

    noise = np.random.uniform(-tnoise, tnoise, (x_val.shape[0], z_input_size))
    yhat = generator.predict([x_val,noise])
    pred_false=discriminator.predict([x_val, yhat])
    acc_false=len(pred_false[pred_false<0.5])/len(y_val)   
    print("pred_false:",pred_false,acc_false)
    file.write(str(acc_false)+'\t')

    noise = np.ones((x_val.shape[0], z_input_size))*tnoise
    yhat = generator.predict([x_val,noise])
    pred_false2=discriminator.predict([x_val, yhat+noise/2.0])
    acc_false2=len(pred_false2[pred_false2<0.5])/len(y_val)   
    print("pred_false2:",pred_false2,acc_false2)
    file.write(str(acc_false2)+'\n')

    print(str(np.sqrt(error))+'\t')

    print(str(acc_true)+'\t'+str(np.mean(pred_true)))
    print(str(acc_false)+'\t'+str(np.mean(pred_false)))
    print(str(acc_false2)+'\t'+str(np.mean(pred_false)))

    
file.close()        
        
    #noise = getNoise()
    #x,true_labels = generate_true_samples(batch_size)
    #fake_labels = generator.predict([x,noise])
    #print("true_labels:",true_labels)
    #print("fake:",fake_labels)
    
    #print("g_loss:",g_loss)
    #print("d_loss:",d_loss)

e: 0
2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 0s/step
0  of  60
108/108 [==============================] - 1s 1ms/step
error0 21.463575
108/108 [==============================] - 0s 1ms/step
[0.88431937 0.901798   0.9013926  ... 0.94261026 0.5264326  0.90193444]
pred_true: [[0.88431937]
 [0.901798  ]
 [0.9013926 ]
 ...
 [0.5264326 ]
 [0.90193444]
 [0.48866802]] 0.772913018096906
108/108 [==============================] - 0s 1ms/step
pred_false: [[0.7426072 ]
 [0.79430324]
 [0.9463899 ]
 ...
 [0.32202396]
 [0.9472558 ]
 [0.4058517 ]] 0.2542323409223584
108/108 [==============================] - 0s 953us/step
pred_false2: [[0.30368093]
 [0.28888845]
 [0.287798  ]
 ...
 [0.27888703]
 [0.28918013]
 [0.30574128]] 1.0
21.463575	
0.772913018096906	0.7106904
0.2542323409223584	0.71588415
1.0	0.71588415
e: 1
2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step
1  of  60
108/108 [==============================] - 0s 1ms/step
error0 19.61269
108/108 [==============================] - 0s 1ms/step
[0.9039451  0.97136223 0.97118026 ... 0.9656539  0.9714268  0.51960075]
pred_true: [[0.9039451 ]
 [0.97136223]
 [0.97118026]
 ...
 [0.49185964]
 [0.9714268 ]
 [0.51960075]] 0.8523058960887332
108/108 [==============================] - 0s 1ms/step
pred_false: [[0.97878313]
 [0.9502478 ]
 [0.95372766]
 ...
 [0.9603785 ]
 [0.9649591 ]
 [0.5476368 ]] 0.14068884997081144
108/108 [==============================] - 0s 1ms/step
pred_false2: [[0.37422615]
 [0.32274207]
 [0.32121795]
 ...
 [0.3094342 ]
 [0.32312414]
 [0.13121794]] 0.9538820782253357
19.61269	
0.8523058960887332	0.7663399
0.14068884997081144	0.79363835
0.9538820782253357	0.79363835
e: 2
2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 0s/step
2  of  60
108/108 [==============================] - 0s 1ms/step
error0 11.661142
108/108 [==============================] - 0s 1ms/step
[0.6942137  0.95750433 0.95750433 ... 0.9319342  0.95750433 0.606249  ]
pred_true: [[0.6942137 ]
 [0.95750433]
 [0.95750433]
 ...
 [0.26372644]
 [0.95750433]
 [0.606249  ]] 0.8143607705779334
108/108 [==============================] - 0s 1ms/step
pred_false: [[0.62615156]
 [0.75045043]
 [0.95601976]
 ...
 [0.13116555]
 [0.7232901 ]
 [0.47346216]] 0.26999416228838297
108/108 [==============================] - 0s 1ms/step
pred_false2: [[0.12743251]
 [0.12776275]
 [0.12725951]
 ...
 [0.12983601]
 [0.12678027]
 [0.13196869]] 0.9489200233508465
11.661142	
0.8143607705779334	0.7249457
0.26999416228838297	0.64594096
0.9489200233508465	0.64594096
e: 3
2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 0s/step
3  of  60
108/108 [==============================] - 0s 1ms/step
error0 13.620059
108/108 [==============================] - 0s 1ms/step
[0.8253006  0.97174096 0.9717262  ... 0.9461003  0.971762   0.6366107 ]
pred_true: [[0.8253006 ]
 [0.97174096]
 [0.9717262 ]
 ...
 [0.32089934]
 [0.971762  ]
 [0.6366107 ]] 0.8365440747227088
108/108 [==============================] - 0s 1ms/step


108/108 [==============================] - 0s 1ms/step
pred_false: [[0.9770715 ]
 [0.68843967]
 [0.78540343]
 ...
 [0.19338699]
 [0.96395344]
 [0.42971468]] 0.12521891418563924
108/108 [==============================] - 0s 1ms/step
pred_false2: [[0.19754206]
 [0.10726289]
 [0.10719413]
 ...
 [0.16835925]
 [0.10726808]
 [0.02673342]] 0.8870402802101576
13.620059	
0.8365440747227088	0.7484585
0.12521891418563924	0.7596989
0.8870402802101576	0.7596989
e: 4
2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step
4  of  60
108/108 [==============================] - 0s 1ms/step
error0 11.817644
108/108 [==============================] - 0s 1ms/step
[0.7996372  0.97195244 0.9719974  ... 0.94066626 0.97208214 0.52367026]
pred_true: [[0.7996372 ]
 [0.97195244]
 [0.9719974 ]
 ...
 [0.47112486]
 [0.97208214]
 [0.52367026]] 0.7095738470519556
108/108 [==============================] - 0s 1ms/step
pred_false: [[0.9819023 ]
 [0.9595146 ]
 [0.96929383]
 ...
 [0.30358326]
 [0.9588603 ]
 [0.5282309 ]] 0.2530647985989492
108/108 [==============================] - 0s 1ms/step
pred_false2: [[0.3047432 ]
 [0.20518512]
 [0.20524226]
 ...
 [0.31806248]
 [0.20500347]
 [0.01190761]] 0.950379451255108
11.817644	
0.7095738470519556	0.7276319
0.2530647985989492	0.68669045
0.950379451255108	0.68669045
e: 5
2/2 [==============================] - 0s 5ms/step


2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 2ms/step
5  of  60
108/108 [==============================] - 0s 1ms/step
error0 13.647894
108/108 [==============================] - 0s 1ms/step
[0.871165   0.9835586  0.98363155 ... 0.56955767 0.98367494 0.5458523 ]
pred_true: [[0.871165  ]
 [0.9835586 ]
 [0.98363155]
 ...
 [0.56955767]
 [0.98367494]
 [0.5458523 ]] 0.8260361938120256
108/108 [==============================] - 0s 1ms/step
pred_false: [[0.9921399 ]
 [0.9828789 ]
 [0.8640777 ]
 ...
 [0.7805079 ]
 [0.9278107 ]
 [0.50512385]] 0.14302393461762988
108/108 [==============================] - 0s 1ms/step
pred_false2: [[0.3583718 ]
 [0.23605129]
 [0.23677   ]
 ...
 [0.34200865]
 [0.2366535 ]
 [0.0059598 ]] 0.9127262113251605
13.647894	
0.8260361938120256	0.7610327
0.14302393461762988	0.7944011
0.9127262113251605	0.7944011
e: 6
2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step
6  of  60
108/108 [==============================] - 0s 1ms/step
error0 8.931011
108/108 [==============================] - 0s 1ms/step
[0.85123205 0.98709226 0.98709226 ... 0.9669753  0.98709226 0.6005598 ]
pred_true: [[0.85123205]
 [0.98709226]
 [0.98709226]
 ...
 [0.42718768]
 [0.98709226]
 [0.6005598 ]] 0.8893753648569761
108/108 [==============================] - 0s 1ms/step
pred_false: [[0.52112836]
 [0.98246056]
 [0.9864629 ]
 ...
 [0.36802253]
 [0.93002915]
 [0.58611345]] 0.08114419147694103
108/108 [==============================] - 0s 1ms/step
pred_false2: [[0.20392509]
 [0.0793169 ]
 [0.07929538]
 ...
 [0.28313997]
 [0.07922634]
 [0.05641106]] 0.8569760653823701
8.931011	
0.8893753648569761	0.76443464
0.08114419147694103	0.75052905
0.8569760653823701	0.75052905
e: 7
2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 2ms/step
7  of  60


108/108 [==============================] - 0s 2ms/step
error0 13.534568
108/108 [==============================] - 0s 1ms/step
[0.84834284 0.9848609  0.9848622  ... 0.53846157 0.98488164 0.57332426]
pred_true: [[0.84834284]
 [0.9848609 ]
 [0.9848622 ]
 ...
 [0.53846157]
 [0.98488164]
 [0.57332426]] 0.8747810858143608
108/108 [==============================] - 0s 1ms/step
pred_false: [[0.9573006 ]
 [0.98480827]
 [0.9829819 ]
 ...
 [0.7326824 ]
 [0.9845177 ]
 [0.5039726 ]] 0.10157618213660245
108/108 [==============================] - 0s 1ms/step
pred_false2: [[0.28421324]
 [0.14493279]
 [0.14492103]
 ...
 [0.31150842]
 [0.14496411]
 [0.00475272]] 0.8998832457676591
13.534568	
0.8747810858143608	0.764873
0.10157618213660245	0.8149588
0.8998832457676591	0.8149588
e: 8
2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step
8  of  60
108/108 [==============================] - 0s 1ms/step
error0 10.539901
108/108 [==============================] - 0s 1ms/step
[0.7714538  0.9547429  0.9547429  ... 0.88154566 0.9547429  0.557263  ]
pred_true: [[0.7714538]
 [0.9547429]
 [0.9547429]
 ...
 [0.4889435]
 [0.9547429]
 [0.557263 ]] 0.801517805020432
108/108 [==============================] - 0s 1ms/step
pred_false: [[0.9118633 ]
 [0.94781536]
 [0.91540253]
 ...
 [0.73312247]
 [0.94973564]
 [0.4726224 ]] 0.22533566841798014
108/108 [==============================] - 0s 1ms/step
pred_false2: [[0.16101597]
 [0.11392231]
 [0.11346056]
 ...
 [0.30803472]
 [0.11148968]
 [0.02653287]] 0.9244016345592527
10.539901	
0.801517805020432	0.7314013
0.22533566841798014	0.67703074
0.9244016345592527	0.67703074
e: 9
2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 2ms/step
9  of  60
108/108 [==============================] - 0s 1ms/step
error0 14.520655
108/108 [==============================] - 0s 1ms/step
[0.9116137  0.98381877 0.98381877 ... 0.9719215  0.98381877 0.57556325]
pred_true: [[0.9116137 ]
 [0.98381877]
 [0.98381877]
 ...
 [0.4330515 ]
 [0.98381877]
 [0.57556325]] 0.8117338003502627
108/108 [==============================] - 0s 1ms/step
pred_false: [[0.16045888]
 [0.26907462]
 [0.93291837]
 ...
 [0.27105787]
 [0.33720568]
 [0.5329321 ]] 0.3312901342673672
108/108 [==============================] - 0s 1ms/step
pred_false2: [[1.3713713e-01]
 [6.3294694e-02]
 [6.3268468e-02]
 ...
 [3.1044909e-01]
 [6.3127063e-02]
 [1.4853933e-04]] 0.9156450671336835
14.520655	
0.8117338003502627	0.75406945
0.3312901342673672	0.6459918
0.9156450671336835	0.6459918
e: 10
2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 1ms/step


2/2 [==============================] - 0s 2ms/step
10  of  60
108/108 [==============================] - 0s 1ms/step
error0 12.439736
108/108 [==============================] - 0s 1ms/step
[0.80226547 0.97101396 0.97101396 ... 0.5247832  0.97101396 0.51217836]
pred_true: [[0.80226547]
 [0.97101396]
 [0.97101396]
 ...
 [0.5247832 ]
 [0.97101396]
 [0.51217836]] 0.8274956217162872
108/108 [==============================] - 0s 1ms/step
pred_false: [[0.98567355]
 [0.9681817 ]
 [0.97083855]
 ...
 [0.9933718 ]
 [0.9684257 ]
 [0.5083024 ]] 0.14623467600700527
108/108 [==============================] - 0s 1ms/step
pred_false2: [[0.21876696]
 [0.12077309]
 [0.12076902]
 ...
 [0.35759482]
 [0.12072792]
 [0.00082083]] 0.9188558085230589
12.439736	
0.8274956217162872	0.74488664
0.14623467600700527	0.8104543
0.9188558085230589	0.8104543
e: 11
2/2 [==============================] - 0s 5ms/step


2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step
11  of  60
108/108 [==============================] - 0s 1ms/step
error0 17.17715
108/108 [==============================] - 0s 1ms/step
[0.80079514 0.98056626 0.98079664 ... 0.51996297 0.9820739  0.60199535]
pred_true: [[0.80079514]
 [0.98056626]
 [0.98079664]
 ...
 [0.51996297]
 [0.9820739 ]
 [0.60199535]] 0.8493870402802102
108/108 [==============================] - 0s 1ms/step
pred_false: [[0.9956911 ]
 [0.98055863]
 [0.9807964 ]
 ...
 [0.98683375]
 [0.9820739 ]
 [0.555127  ]] 0.03823701109165207
108/108 [==============================] - 0s 1ms/step
pred_false2: [[0.21015042]
 [0.05425999]
 [0.05488745]
 ...
 [0.38450453]
 [0.05864072]
 [0.01056595]] 0.8852889667250438
17.17715	
0.8493870402802102	0.76109976
0.03823701109165207	0.8468853
0.8852889667250438	0.8468853
e: 12
2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 0s/step
12  of  60
108/108 [==============================] - 0s 1ms/step
error0 10.43421
108/108 [==============================] - 0s 1ms/step
[0.52396864 0.9837061  0.9837061  ... 0.95382196 0.9837061  0.5419602 ]
pred_true: [[0.52396864]
 [0.9837061 ]
 [0.9837061 ]
 ...
 [0.35402295]
 [0.9837061 ]
 [0.5419602 ]] 0.8000583771161704
108/108 [==============================] - 0s 1ms/step
pred_false: [[0.9653428 ]
 [0.9646944 ]
 [0.978814  ]
 ...
 [0.96972984]
 [0.98179024]
 [0.5128944 ]] 0.10245183887915937
108/108 [==============================] - 0s 1ms/step
pred_false2: [[0.04888759]
 [0.05793104]
 [0.05791585]
 ...
 [0.21673727]
 [0.05771625]
 [0.00105943]] 0.8884997081144191
10.43421	
0.8000583771161704	0.73798764
0.10245183887915937	0.79948354
0.8884997081144191	0.79948354
e: 13
2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 2ms/step
13  of  60
108/108 [==============================] - 0s 1ms/step
error0 8.244648
108/108 [==============================] - 0s 1ms/step
[0.62222844 0.97958386 0.979584   ... 0.9427138  0.97982144 0.5836648 ]
pred_true: [[0.62222844]
 [0.97958386]
 [0.979584  ]
 ...
 [0.45947325]
 [0.97982144]
 [0.5836648 ]] 0.8537653239929948
108/108 [==============================] - 0s 1ms/step
pred_false: [[0.9496741]
 [0.9689269]
 [0.8693843]
 ...
 [0.9269841]
 [0.9771955]
 [0.51274  ]] 0.1587857559836544
108/108 [==============================] - 0s 1ms/step
pred_false2: [[0.09346204]
 [0.04046945]
 [0.04042298]
 ...
 [0.3228619 ]
 [0.04030097]
 [0.00033069]] 0.8695271453590193
8.244648	
0.8537653239929948	0.74696404
0.1587857559836544	0.72384125
0.8695271453590193	0.72384125
e: 14
2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 0s/step
14  of  60
108/108 [==============================] - 0s 1ms/step
error0 10.035711
108/108 [==============================] - 0s 1ms/step
[0.79756993 0.99469846 0.99469894 ... 0.5434051  0.99474865 0.5790183 ]
pred_true: [[0.79756993]
 [0.99469846]
 [0.99469894]
 ...
 [0.5434051 ]
 [0.99474865]
 [0.5790183 ]] 0.8517221249270286
108/108 [==============================] - 0s 1ms/step
pred_false: [[0.9963914 ]
 [0.99450356]
 [0.99458975]
 ...
 [0.86104   ]
 [0.9836733 ]
 [0.5618587 ]] 0.14302393461762988
108/108 [==============================] - 0s 1ms/step
pred_false2: [[1.6081195e-01]
 [9.9133290e-02]
 [9.9135645e-02]
 ...
 [3.4044191e-01]
 [9.9193484e-02]
 [8.6650150e-05]] 0.8806187974314069
10.035711	
0.8517221249270286	0.77215564
0.14302393461762988	0.7584892
0.8806187974314069	0.7584892
e: 15
2/2 [==============================] - 0s 16ms/step


2/2 [==============================] - 0s 16ms/step


2/2 [==============================] - 0s 16ms/step


2/2 [==============================] - 0s 3ms/step
15  of  60
108/108 [==============================] - 0s 1ms/step
error0 13.217917
108/108 [==============================] - 0s 1ms/step
[0.7541118 0.9901494 0.9901424 ... 0.535977  0.9904994 0.6113491]
pred_true: [[0.7541118]
 [0.9901494]
 [0.9901424]
 ...
 [0.535977 ]
 [0.9904994]
 [0.6113491]] 0.8925861062463515
108/108 [==============================] - 0s 1ms/step
pred_false: [[0.99574   ]
 [0.9900988 ]
 [0.98949337]
 ...
 [0.99449736]
 [0.9899913 ]
 [0.52391404]] 0.06509048453006422
108/108 [==============================] - 0s 1ms/step
pred_false2: [[1.6800818e-01]
 [5.7227410e-02]
 [5.7181828e-02]
 ...
 [3.4217763e-01]
 [5.9140854e-02]
 [3.5109799e-05]] 0.9086398131932283
13.217917	
0.8925861062463515	0.7721476
0.06509048453006422	0.8252767
0.9086398131932283	0.8252767
e: 16
2/2 [==============================] - 0s 12ms/step


2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 0s/step
16  of  60
108/108 [==============================] - 0s 1ms/step
error0 9.024754
108/108 [==============================] - 0s 1ms/step
[0.9263007  0.9958393  0.99584377 ... 0.6401352  0.9960126  0.5966179 ]
pred_true: [[0.9263007 ]
 [0.9958393 ]
 [0.99584377]
 ...
 [0.6401352 ]
 [0.9960126 ]
 [0.5966179 ]] 0.9681844716870986
108/108 [==============================] - 0s 1ms/step
pred_false: [[0.97808343]
 [0.8595273 ]
 [0.9926166 ]
 ...
 [0.96914643]
 [0.9959091 ]
 [0.52108693]] 0.03852889667250438
108/108 [==============================] - 0s 1ms/step
pred_false2: [[0.21352686]
 [0.07431936]
 [0.07427505]
 ...
 [0.39784604]
 [0.07614883]
 [0.0040746 ]] 0.836835960303561
9.024754	
0.9681844716870986	0.7954156
0.03852889667250438	0.7973014
0.836835960303561	0.7973014
e: 17


2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 3ms/step
17  of  60
108/108 [==============================] - 0s 1ms/step
error0 9.664162
108/108 [==============================] - 0s 1ms/step
[0.9422578  0.99190074 0.99190986 ... 0.6954231  0.9923668  0.594721  ]
pred_true: [[0.9422578 ]
 [0.99190074]
 [0.99190986]
 ...
 [0.6954231 ]
 [0.9923668 ]
 [0.594721  ]] 0.9518388791593695
108/108 [==============================] - 0s 1ms/step
pred_false: [[0.7032555 ]
 [0.6932579 ]
 [0.9698787 ]
 ...
 [0.5255623 ]
 [0.77173257]
 [0.5943488 ]] 0.14273204903677758
108/108 [==============================] - 0s 1ms/step
pred_false2: [[0.25489148]
 [0.1075326 ]
 [0.10759925]
 ...
 [0.4113942 ]
 [0.1130624 ]
 [0.00047397]] 0.8788674839462931
9.664162	
0.9518388791593695	0.7934754
0.14273204903677758	0.7309003
0.8788674839462931	0.7309003
e: 18
2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 0s/step
18  of  60
108/108 [==============================] - 0s 1ms/step
error0 8.343082
108/108 [==============================] - 0s 1ms/step
[0.8870967  0.99702203 0.9970187  ... 0.5634794  0.9970621  0.6063171 ]
pred_true: [[0.8870967 ]
 [0.99702203]
 [0.9970187 ]
 ...
 [0.5634794 ]
 [0.9970621 ]
 [0.6063171 ]] 0.9249854057209573
108/108 [==============================] - 0s 1ms/step
pred_false: [[0.78611714]
 [0.9608389 ]
 [0.9298056 ]
 ...
 [0.893974  ]
 [0.9964886 ]
 [0.5210386 ]] 0.198482194979568
108/108 [==============================] - 0s 1ms/step
pred_false2: [[1.2664695e-01]
 [6.1177343e-02]
 [6.0739875e-02]
 ...
 [3.4907478e-01]
 [5.8884133e-02]
 [3.1157699e-05]] 0.8955049620548745
8.343082	
0.9249854057209573	0.78542763
0.198482194979568	0.6988452
0.8955049620548745	0.6988452
e: 19
2/2 [==============================] - 0s 999us/step


2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step
19  of  60
108/108 [==============================] - 0s 1ms/step
error0 8.795963
108/108 [==============================] - 0s 1ms/step
[0.7899687  0.97295296 0.97295904 ... 0.5420185  0.97406167 0.591804  ]
pred_true: [[0.7899687 ]
 [0.97295296]
 [0.97295904]
 ...
 [0.5420185 ]
 [0.97406167]
 [0.591804  ]] 0.9130180969060129
108/108 [==============================] - 0s 1ms/step
pred_false: [[0.95394707]
 [0.9750725 ]
 [0.9858342 ]
 ...
 [0.3464519 ]
 [0.34243706]
 [0.5866187 ]] 0.14915353181552832
108/108 [==============================] - 0s 1ms/step
pred_false2: [[0.14332004]
 [0.06642904]
 [0.06625599]
 ...
 [0.36074245]
 [0.06718415]
 [0.00162083]] 0.8689433741973146
8.795963	
0.9130180969060129	0.76542246
0.14915353181552832	0.737247
0.8689433741973146	0.737247
e: 20
2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 3ms/step
20  of  60
108/108 [==============================] - 0s 2ms/step
error0 9.972253
108/108 [==============================] - 0s 1ms/step
[0.9201374  0.9956403  0.9956618  ... 0.55552596 0.9961886  0.5926794 ]
pred_true: [[0.9201374 ]
 [0.9956403 ]
 [0.9956618 ]
 ...
 [0.55552596]
 [0.9961886 ]
 [0.5926794 ]] 0.9515469935785172
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.99856555]
 [0.944024  ]
 [0.99266124]
 ...
 [0.9892994 ]
 [0.9962181 ]
 [0.5956588 ]] 0.03852889667250438


108/108 [==============================] - 0s 1ms/step
pred_false2: [[0.26166862]
 [0.10173775]
 [0.10208008]
 ...
 [0.41073418]
 [0.11330928]
 [0.04951059]] 0.7907180385288967
9.972253	
0.9515469935785172	0.78810644
0.03852889667250438	0.8227877
0.7907180385288967	0.8227877
e: 21
2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step
21  of  60
108/108 [==============================] - 0s 1ms/step
error0 12.299212
108/108 [==============================] - 0s 1ms/step
[0.9640036  0.9640036  0.9640036  ... 0.9273624  0.9640036  0.57135516]
pred_true: [[0.44857466]
 [0.9640036 ]
 [0.9640036 ]
 ...
 [0.41946805]
 [0.9640036 ]
 [0.57135516]] 0.7200817279626387
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.96948934]
 [0.96400553]
 [0.96427083]
 ...
 [0.99606246]
 [0.964129  ]
 [0.52227014]] 0.11033274956217162
108/108 [==============================] - 0s 1ms/step
pred_false2: [[6.2994055e-02]
 [5.3846482e-02]
 [5.3846400e-02]
 ...
 [3.0879968e-01]
 [5.3845260e-02]
 [1.9859849e-04]] 0.8978400467016929
12.299212	
0.7200817279626387	0.72558486
0.11033274956217162	0.81899995
0.8978400467016929	0.81899995
e: 22
2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 3ms/step
22  of  60
108/108 [==============================] - 0s 2ms/step
error0 12.394053
108/108 [==============================] - 0s 2ms/step
[0.93404555 0.93404555 0.93404555 ... 0.7576394  0.93404555 0.59675556]
pred_true: [[0.41185796]
 [0.93404555]
 [0.93404555]
 ...
 [0.44727612]
 [0.93404555]
 [0.59675556]] 0.8423817863397548
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.93601483]
 [0.93389827]
 [0.9017976 ]
 ...
 [0.92860806]
 [0.89656883]
 [0.5598173 ]] 0.07443082311733801
108/108 [==============================] - 0s 2ms/step
pred_false2: [[6.0523145e-02]
 [2.8859464e-02]
 [2.8850203e-02]
 ...
 [3.1067193e-01]
 [2.8746206e-02]
 [6.7016088e-05]] 0.9045534150612959
12.394053	
0.8423817863397548	0.7059104
0.07443082311733801	0.76268077
0.9045534150612959	0.76268077
e: 23
2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 3ms/step
23  of  60
108/108 [==============================] - 0s 2ms/step
error0 9.647945
108/108 [==============================] - 0s 1ms/step
[0.8392512  0.96186626 0.96187335 ... 0.5448203  0.96456355 0.5798009 ]
pred_true: [[0.8392512 ]
 [0.96186626]
 [0.96187335]
 ...
 [0.5448203 ]
 [0.96456355]
 [0.5798009 ]] 0.9387040280210157
108/108 [==============================] - 0s 1ms/step
pred_false: [[0.99378735]
 [0.5210854 ]
 [0.9859614 ]
 ...
 [0.91957927]
 [0.97829294]
 [0.56792367]] 0.10128429655575015
108/108 [==============================] - 0s 2ms/step
pred_false2: [[0.14892806]
 [0.04591702]
 [0.04584847]
 ...
 [0.3869929 ]
 [0.04808905]
 [0.01157492]] 0.8391710449503794
9.647945	
0.9387040280210157	0.7553909
0.10128429655575015	0.74312085
0.8391710449503794	0.74312085
e: 24
2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 0s/step
24  of  60
108/108 [==============================] - 0s 2ms/step
error0 16.991499
108/108 [==============================] - 0s 2ms/step
[0.59170705 0.973296   0.973296   ... 0.8738404  0.973296   0.5947204 ]
pred_true: [[0.59170705]
 [0.973296  ]
 [0.973296  ]
 ...
 [0.46938524]
 [0.973296  ]
 [0.5947204 ]] 0.8756567425569177
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.99155307]
 [0.97329694]
 [0.973296  ]
 ...
 [0.99835676]
 [0.9732979 ]
 [0.5960377 ]] 0.02130764740221833
108/108 [==============================] - 0s 1ms/step
pred_false2: [[9.1722935e-02]
 [3.0413030e-02]
 [3.0413030e-02]
 ...
 [3.4153995e-01]
 [3.0412992e-02]
 [2.8990067e-05]] 0.9074722708698191
16.991499	
0.8756567425569177	0.7414484
0.02130764740221833	0.83330107
0.9074722708698191	0.83330107
e: 25
2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 6ms/step


2/2 [==============================] - 0s 3ms/step
25  of  60
108/108 [==============================] - 0s 2ms/step
error0 7.6020536
108/108 [==============================] - 0s 2ms/step
[0.87720096 0.9931205  0.9930937  ... 0.5815729  0.99414825 0.5774789 ]
pred_true: [[0.87720096]
 [0.9931205 ]
 [0.9930937 ]
 ...
 [0.5815729 ]
 [0.99414825]
 [0.5774789 ]] 0.9422066549912435
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.73910433]
 [0.47147426]
 [0.9929703 ]
 ...
 [0.9989217 ]
 [0.9903017 ]
 [0.5078137 ]] 0.12200817279626386
108/108 [==============================] - 0s 2ms/step
pred_false2: [[2.6033190e-01]
 [6.2620804e-02]
 [6.2286794e-02]
 ...
 [4.2236504e-01]
 [7.0856504e-02]
 [1.7904222e-05]] 0.8639813193228254
7.6020536	
0.9422066549912435	0.7776779
0.12200817279626386	0.74221087
0.8639813193228254	0.74221087
e: 26
2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 3ms/step
26  of  60
108/108 [==============================] - 0s 2ms/step
error0 10.762023
108/108 [==============================] - 0s 2ms/step
[0.83730906 0.98648477 0.9864447  ... 0.54461044 0.98801714 0.5935126 ]
pred_true: [[0.83730906]
 [0.98648477]
 [0.9864447 ]
 ...
 [0.54461044]
 [0.98801714]
 [0.5935126 ]] 0.8166958552247519
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.9958569 ]
 [0.98006   ]
 [0.98320967]
 ...
 [0.42143822]
 [0.97581524]
 [0.589998  ]] 0.0989492119089317
108/108 [==============================] - 0s 2ms/step
pred_false2: [[1.8055108e-01]
 [7.1912333e-02]
 [7.1679205e-02]
 ...
 [3.3926320e-01]
 [7.9975709e-02]
 [3.2524647e-05]] 0.9039696438995913
10.762023	
0.8166958552247519	0.7661111
0.0989492119089317	0.80578727
0.9039696438995913	0.80578727
e: 27
2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 3ms/step
27  of  60
108/108 [==============================] - 0s 2ms/step
error0 10.97858
108/108 [==============================] - 0s 2ms/step
[0.77621245 0.9629722  0.96288234 ... 0.8989639  0.965623   0.5240136 ]
pred_true: [[0.77621245]
 [0.9629722 ]
 [0.96288234]
 ...
 [0.4779674 ]
 [0.965623  ]
 [0.5240136 ]] 0.6900175131348512
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.6284481 ]
 [0.9060512 ]
 [0.96240205]
 ...
 [0.9428075 ]
 [0.9531696 ]
 [0.5240136 ]] 0.22358435493286632
108/108 [==============================] - 0s 2ms/step
pred_false2: [[3.0497327e-01]
 [1.9558670e-01]
 [1.9507122e-01]
 ...
 [3.6933008e-01]
 [2.0616332e-01]
 [6.3872794e-05]] 0.9538820782253357
10.97858	
0.6900175131348512	0.72357476
0.22358435493286632	0.7259429
0.9538820782253357	0.7259429
e: 28
2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 3ms/step
28  of  60
108/108 [==============================] - 0s 2ms/step
error0 12.495936
108/108 [==============================] - 0s 2ms/step
[0.844374   0.97794664 0.9779216  ... 0.57938945 0.98097503 0.56436753]
pred_true: [[0.844374  ]
 [0.97794664]
 [0.9779216 ]
 ...
 [0.57938945]
 [0.98097503]
 [0.56436753]] 0.794804436660829
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.99313426]
 [0.977995  ]
 [0.9711413 ]
 ...
 [0.57129663]
 [0.74746346]
 [0.49225345]] 0.1625802685347344
108/108 [==============================] - 0s 2ms/step
pred_false2: [[2.2040589e-01]
 [7.3906451e-02]
 [7.3790610e-02]
 ...
 [3.9107934e-01]
 [8.4348597e-02]
 [5.8255778e-06]] 0.9121424401634559
12.495936	
0.794804436660829	0.7623331
0.1625802685347344	0.7866623
0.9121424401634559	0.7866623
e: 29
2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 0s/step
29  of  60
108/108 [==============================] - 0s 2ms/step
error0 9.821494
108/108 [==============================] - 0s 2ms/step
[0.81062716 0.98486817 0.98486817 ... 0.5328819  0.98486817 0.57030374]
pred_true: [[0.81062716]
 [0.98486817]
 [0.98486817]
 ...
 [0.5328819 ]
 [0.98486817]
 [0.57030374]] 0.8064798598949212
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.97194207]
 [0.9816704 ]
 [0.9317621 ]
 ...
 [0.61785036]
 [0.98465985]
 [0.5643174 ]] 0.16579100992410975
108/108 [==============================] - 0s 2ms/step


108/108 [==============================] - 0s 2ms/step
pred_false2: [[1.2448630e-01]
 [5.4101966e-02]
 [5.3989828e-02]
 ...
 [3.5934409e-01]
 [5.2868437e-02]
 [1.0618436e-04]] 0.87594862813777
9.821494	
0.8064798598949212	0.76119536
0.16579100992410975	0.74257016
0.87594862813777	0.74257016
e: 30
2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 3ms/step
30  of  60
108/108 [==============================] - 0s 2ms/step
error0 9.915685
108/108 [==============================] - 0s 2ms/step
[0.9307367  0.9931083  0.9930972  ... 0.69594043 0.993887   0.5887951 ]
pred_true: [[0.9307367 ]
 [0.9931083 ]
 [0.9930972 ]
 ...
 [0.69594043]
 [0.993887  ]
 [0.5887951 ]] 0.9316987740805605
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.9179144 ]
 [0.9893295 ]
 [0.991957  ]
 ...
 [0.44681254]
 [0.994041  ]
 [0.51669884]] 0.04932866316403969
108/108 [==============================] - 0s 2ms/step
pred_false2: [[3.2093596e-01]
 [1.8301222e-01]
 [1.8264988e-01]
 ...
 [3.7397066e-01]
 [2.0018812e-01]
 [1.0352062e-05]] 0.8960887332165791
9.915685	
0.9316987740805605	0.79206806
0.04932866316403969	0.8241874
0.8960887332165791	0.8241874
e: 31
2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step
31  of  60
108/108 [==============================] - 0s 2ms/step
error0 10.179343
108/108 [==============================] - 0s 2ms/step
[0.8833526  0.9865236  0.98649776 ... 0.59719986 0.9875563  0.5746925 ]
pred_true: [[0.8833526 ]
 [0.9865236 ]
 [0.98649776]
 ...
 [0.59719986]
 [0.9875563 ]
 [0.5746925 ]] 0.9632224168126094
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.50220317]
 [0.8590418 ]
 [0.9819255 ]
 ...
 [0.39475596]
 [0.9168433 ]
 [0.5746925 ]] 0.05224751897256275
108/108 [==============================] - 0s 2ms/step
pred_false2: [[1.84985459e-01]
 [9.95542482e-02]
 [9.92096290e-02]
 ...
 [3.97041231e-01]
 [1.05125375e-01]
 [4.07383341e-05]] 0.8607705779334501
10.179343	
0.9632224168126094	0.77963436
0.05224751897256275	0.75705826
0.8607705779334501	0.75705826
e: 32
2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 0s/step
32  of  60
108/108 [==============================] - 0s 2ms/step
error0 10.532841
108/108 [==============================] - 0s 2ms/step
[0.8661055  0.9797483  0.9797483  ... 0.5271144  0.9797483  0.57504743]
pred_true: [[0.8661055 ]
 [0.9797483 ]
 [0.9797483 ]
 ...
 [0.5271144 ]
 [0.9797483 ]
 [0.57504743]] 0.8995913601868067
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.9947493 ]
 [0.98251337]
 [0.9832806 ]
 ...
 [0.37485558]
 [0.7358582 ]
 [0.57504743]] 0.07589025102159953
108/108 [==============================] - 0s 2ms/step
pred_false2: [[1.3967390e-01]
 [5.2249115e-02]
 [5.2170016e-02]
 ...
 [3.7669414e-01]
 [5.1375419e-02]
 [2.2201315e-05]] 0.8776999416228838
10.532841	
0.8995913601868067	0.76380485
0.07589025102159953	0.76840407
0.8776999416228838	0.76840407
e: 33
2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 13ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 17ms/step
33  of  60
108/108 [==============================] - 0s 2ms/step
error0 11.754213
108/108 [==============================] - 0s 2ms/step
[0.84875953 0.9732636  0.97330093 ... 0.9418892  0.97602785 0.5325097 ]
pred_true: [[0.84875953]
 [0.9732636 ]
 [0.97330093]
 ...
 [0.46707362]
 [0.97602785]
 [0.5325097 ]] 0.7335084646818447
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.98724306]
 [0.9391831 ]
 [0.8936376 ]
 ...
 [0.44460675]
 [0.97588325]
 [0.5325097 ]] 0.15469935785172212
108/108 [==============================] - 0s 2ms/step
pred_false2: [[0.11800647]
 [0.05361983]
 [0.05366788]
 ...
 [0.32510796]
 [0.05927369]
 [0.00127804]] 0.8823701109165207
11.754213	
0.7335084646818447	0.74212277
0.15469935785172212	0.7846205
0.8823701109165207	0.7846205
e: 34
2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 3ms/step
34  of  60
108/108 [==============================] - 0s 2ms/step
error0 8.679954
108/108 [==============================] - 0s 2ms/step
[0.9106997  0.99685293 0.9968561  ... 0.60058486 0.99746037 0.60647386]
pred_true: [[0.9106997 ]
 [0.99685293]
 [0.9968561 ]
 ...
 [0.60058486]
 [0.99746037]
 [0.60647386]] 0.9938704028021016
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.999616  ]
 [0.958851  ]
 [0.99706525]
 ...
 [0.57452625]
 [0.9973545 ]
 [0.60647386]] 0.10303561004086398
108/108 [==============================] - 0s 2ms/step
pred_false2: [[0.18427677]
 [0.03454281]
 [0.03449506]
 ...
 [0.4298856 ]
 [0.04139212]
 [0.00275211]] 0.8096906012842966
8.679954	
0.9938704028021016	0.7926785
0.10303561004086398	0.76540667
0.8096906012842966	0.76540667
e: 35
2/2 [==============================] - 0s 16ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 13ms/step


2/2 [==============================] - 0s 3ms/step
35  of  60
108/108 [==============================] - 0s 2ms/step
error0 11.199179
108/108 [==============================] - 0s 2ms/step
[0.7648691  0.99263287 0.99263287 ... 0.5299125  0.9926329  0.5789874 ]
pred_true: [[0.7648691 ]
 [0.99263287]
 [0.99263287]
 ...
 [0.5299125 ]
 [0.9926329 ]
 [0.5789874 ]] 0.7399299474605955
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.9723367 ]
 [0.9922564 ]
 [0.99248075]
 ...
 [0.95613426]
 [0.9912593 ]
 [0.4920465 ]] 0.14010507880910683
108/108 [==============================] - 0s 2ms/step
pred_false2: [[1.0888093e-01]
 [2.0411797e-02]
 [2.0407896e-02]
 ...
 [3.6873618e-01]
 [2.0369448e-02]
 [1.9421625e-06]] 0.900758902510216
11.199179	
0.7399299474605955	0.7591295
0.14010507880910683	0.8288821
0.900758902510216	0.8288821
e: 36
2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 6ms/step
36  of  60
108/108 [==============================] - 0s 2ms/step
error0 9.1684475
108/108 [==============================] - 0s 2ms/step
[0.8722313  0.9861876  0.98618937 ... 0.62252086 0.98627347 0.569418  ]
pred_true: [[0.8722313 ]
 [0.9861876 ]
 [0.98618937]
 ...
 [0.62252086]
 [0.98627347]
 [0.569418  ]] 0.9162288382953883
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.8803988]
 [0.8693855]
 [0.9359259]
 ...
 [0.5586798]
 [0.4950867]
 [0.5285002]] 0.14594279042615294
108/108 [==============================] - 0s 2ms/step
pred_false2: [[1.3047744e-01]
 [9.7713105e-02]
 [9.7488046e-02]
 ...
 [3.6322087e-01]
 [9.5562756e-02]
 [2.6691065e-04]] 0.8987157034442499
9.1684475	
0.9162288382953883	0.78088975
0.14594279042615294	0.7267729
0.8987157034442499	0.7267729
e: 37
2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 6ms/step
37  of  60
108/108 [==============================] - 0s 2ms/step
error0 13.940288
108/108 [==============================] - 0s 2ms/step
[0.83867955 0.9887313  0.9887313  ... 0.61942905 0.9887313  0.58890575]
pred_true: [[0.83867955]
 [0.9887313 ]
 [0.9887313 ]
 ...
 [0.61942905]
 [0.9887313 ]
 [0.58890575]] 0.9217746643315821
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.80798835]
 [0.98800063]
 [0.98653924]
 ...
 [0.84392446]
 [0.933283  ]
 [0.58890575]] 0.04611792177466433
108/108 [==============================] - 0s 2ms/step
pred_false2: [[0.14676298]
 [0.0884736 ]
 [0.08848041]
 ...
 [0.36424884]
 [0.08815054]
 [0.0074791 ]] 0.8698190309398716
13.940288	
0.9217746643315821	0.7762195
0.04611792177466433	0.8221804
0.8698190309398716	0.8221804
e: 38
2/2 [==============================] - 0s 5ms/step


2/2 [==============================] - 0s 5ms/step


2/2 [==============================] - 0s 4ms/step
38  of  60
108/108 [==============================] - 0s 4ms/step
error0 10.388309
108/108 [==============================] - 0s 3ms/step
[0.82385045 0.9738548  0.9738548  ... 0.5420463  0.9738548  0.57414716]
pred_true: [[0.82385045]
 [0.9738548 ]
 [0.9738548 ]
 ...
 [0.5420463 ]
 [0.9738548 ]
 [0.57414716]] 0.8309982486865148
108/108 [==============================] - 0s 3ms/step
pred_false: [[0.9889518 ]
 [0.9691228 ]
 [0.9705171 ]
 ...
 [0.36571237]
 [0.9724631 ]
 [0.49929252]] 0.11938120256859311
108/108 [==============================] - 0s 2ms/step
pred_false2: [[1.3504520e-01]
 [6.9321558e-02]
 [6.9266275e-02]
 ...
 [3.6422500e-01]
 [6.8588465e-02]
 [3.2743689e-04]] 0.9045534150612959
10.388309	
0.8309982486865148	0.7548955
0.11938120256859311	0.7792041
0.9045534150612959	0.7792041
e: 39
2/2 [==============================] - 0s 6ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 3ms/step
39  of  60
108/108 [==============================] - 0s 2ms/step
error0 8.594532
108/108 [==============================] - 0s 2ms/step
[0.8653983  0.9986115  0.9986112  ... 0.5669474  0.99883956 0.5896226 ]
pred_true: [[0.8653983 ]
 [0.9986115 ]
 [0.9986112 ]
 ...
 [0.5669474 ]
 [0.99883956]
 [0.5896226 ]] 0.9173963806187975
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.80071366]
 [0.98718286]
 [0.15974595]
 ...
 [0.65969145]
 [0.9909799 ]
 [0.5536987 ]] 0.20081727962638646
108/108 [==============================] - 0s 2ms/step
pred_false2: [[1.4858980e-01]
 [4.1315556e-02]
 [4.1162036e-02]
 ...
 [3.7188268e-01]
 [4.6444852e-02]
 [6.5760396e-05]] 0.854932866316404
8.594532	
0.9173963806187975	0.78363323
0.20081727962638646	0.6774667
0.854932866316404	0.6774667
e: 40
2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 14ms/step


2/2 [==============================] - 0s 0s/step
40  of  60
108/108 [==============================] - 0s 2ms/step
error0 8.123429
108/108 [==============================] - 0s 2ms/step
[0.8927369 0.9961379 0.9961356 ... 0.6756749 0.9966719 0.5849588]
pred_true: [[0.8927369]
 [0.9961379]
 [0.9961356]
 ...
 [0.6756749]
 [0.9966719]
 [0.5849588]] 0.9603035610040864
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.4285899 ]
 [0.412897  ]
 [0.6797751 ]
 ...
 [0.38679323]
 [0.73007053]
 [0.56590915]] 0.12259194395796848
108/108 [==============================] - 0s 2ms/step
pred_false2: [[1.6797379e-01]
 [7.9488426e-02]
 [7.9342097e-02]
 ...
 [3.8797528e-01]
 [8.8968746e-02]
 [2.5521764e-05]] 0.8450087565674256
8.123429	
0.9603035610040864	0.79338306
0.12259194395796848	0.73295313
0.8450087565674256	0.73295313
e: 41
2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 3ms/step


2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 0s/step
41  of  60
108/108 [==============================] - 0s 2ms/step
error0 10.530016
108/108 [==============================] - 0s 2ms/step
[0.9352973  0.9938015  0.9937803  ... 0.63066906 0.994668   0.59081703]
pred_true: [[0.9352973 ]
 [0.9938015 ]
 [0.9937803 ]
 ...
 [0.63066906]
 [0.994668  ]
 [0.59081703]] 0.9804436660828955
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.49800062]
 [0.9866512 ]
 [0.9925623 ]
 ...
 [0.60090494]
 [0.9585029 ]
 [0.5781612 ]] 0.04407472270869819
108/108 [==============================] - 0s 2ms/step
pred_false2: [[3.0069616e-01]
 [1.7577614e-01]
 [1.7509493e-01]
 ...
 [4.2163146e-01]
 [1.9625430e-01]
 [2.2711627e-06]] 0.8771161704611792
10.530016	
0.9804436660828955	0.7919719
0.04407472270869819	0.80240756
0.8771161704611792	0.80240756
e: 42
2/2 [==============================] - 0s 14ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 3ms/step
42  of  60
108/108 [==============================] - 0s 2ms/step
error0 11.077351
108/108 [==============================] - 0s 2ms/step
[0.8424126 0.9878418 0.9878418 ... 0.5575795 0.9878418 0.5915012]
pred_true: [[0.8424126]
 [0.9878418]
 [0.9878418]
 ...
 [0.5575795]
 [0.9878418]
 [0.5915012]] 0.8604786923525978
108/108 [==============================] - 0s 2ms/step


108/108 [==============================] - 0s 2ms/step
pred_false: [[0.9812849 ]
 [0.8882424 ]
 [0.98647016]
 ...
 [0.3406119 ]
 [0.9867806 ]
 [0.5098705 ]] 0.10799766491535318
108/108 [==============================] - 0s 2ms/step
pred_false2: [[9.1679737e-02]
 [4.1711695e-02]
 [4.1644566e-02]
 ...
 [3.6524558e-01]
 [4.0494248e-02]
 [5.7126721e-07]] 0.9258610624635143
11.077351	
0.8604786923525978	0.7703259
0.10799766491535318	0.7707579
0.9258610624635143	0.7707579
e: 43
2/2 [==============================] - 0s 10ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step
43  of  60
108/108 [==============================] - 0s 2ms/step
error0 8.038899
108/108 [==============================] - 0s 2ms/step
[0.82267416 0.99087334 0.99087334 ... 0.534957   0.99087334 0.5808668 ]
pred_true: [[0.82267416]
 [0.99087334]
 [0.99087334]
 ...
 [0.534957  ]
 [0.99087334]
 [0.5808668 ]] 0.8704028021015762
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.99687517]
 [0.8860269 ]
 [0.99043983]
 ...
 [0.6764671 ]
 [0.99036026]
 [0.5808668 ]] 0.07180385288966724
108/108 [==============================] - 0s 3ms/step
pred_false2: [[1.3187738e-01]
 [5.9048086e-02]
 [5.9019603e-02]
 ...
 [3.4793937e-01]
 [5.8591973e-02]
 [2.7688038e-06]] 0.8949211908931699
8.038899	
0.8704028021015762	0.77047706
0.07180385288966724	0.78936034
0.8949211908931699	0.78936034
e: 44
2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 5ms/step
44  of  60
108/108 [==============================] - 0s 3ms/step
error0 9.210082
108/108 [==============================] - 0s 3ms/step
[0.9183422  0.99103266 0.9910307  ... 0.6043854  0.9913883  0.576034  ]
pred_true: [[0.9183422 ]
 [0.99103266]
 [0.9910307 ]
 ...
 [0.6043854 ]
 [0.9913883 ]
 [0.576034  ]] 0.8908347927612376
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.90419495]
 [0.9884004 ]
 [0.78311133]
 ...
 [0.9938642 ]
 [0.86634165]
 [0.5140054 ]] 0.08231173380035026
108/108 [==============================] - 0s 2ms/step
pred_false2: [[1.8132968e-01]
 [9.1215245e-02]
 [9.1052875e-02]
 ...
 [3.7769356e-01]
 [9.2909448e-02]
 [4.7109943e-06]] 0.8800350262697023
9.210082	
0.8908347927612376	0.78213376
0.08231173380035026	0.7564949
0.8800350262697023	0.7564949
e: 45
2/2 [==============================] - 0s 17ms/step


2/2 [==============================] - 0s 5ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step
45  of  60
108/108 [==============================] - 0s 3ms/step
error0 12.48208
108/108 [==============================] - 0s 2ms/step
[0.82307184 0.99229115 0.99229115 ... 0.56710875 0.99229115 0.5816183 ]
pred_true: [[0.82307184]
 [0.99229115]
 [0.99229115]
 ...
 [0.56710875]
 [0.99229115]
 [0.5816183 ]] 0.8464681844716871
108/108 [==============================] - 0s 3ms/step
pred_false: [[0.39163622]
 [0.9908957 ]
 [0.99226713]
 ...
 [0.39354137]
 [0.99110734]
 [0.4139046 ]] 0.11646234676007006
108/108 [==============================] - 0s 4ms/step
pred_false2: [[1.3674057e-01]
 [3.8542438e-02]
 [3.8513370e-02]
 ...
 [3.9460382e-01]
 [3.8241874e-02]
 [2.0404903e-07]] 0.8966725043782837
12.48208	
0.8464681844716871	0.7680785
0.11646234676007006	0.79056656
0.8966725043782837	0.79056656
e: 46
2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 14ms/step


2/2 [==============================] - 0s 5ms/step


2/2 [==============================] - 0s 11ms/step
46  of  60
108/108 [==============================] - 0s 2ms/step
error0 11.25669
108/108 [==============================] - 0s 3ms/step
[0.8440099  0.9946844  0.9946844  ... 0.5690713  0.9946844  0.58905005]
pred_true: [[0.8440099 ]
 [0.9946844 ]
 [0.9946844 ]
 ...
 [0.5690713 ]
 [0.9946844 ]
 [0.58905005]] 0.8423817863397548
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.99433494]
 [0.99064165]
 [0.99320835]
 ...
 [0.9989603 ]
 [0.99186486]
 [0.58905005]] 0.07530647985989491
108/108 [==============================] - 0s 2ms/step
pred_false2: [[1.0990174e-01]
 [2.4536461e-02]
 [2.4527768e-02]
 ...
 [3.6212879e-01]
 [2.4428716e-02]
 [6.3963699e-07]] 0.9083479276123759
11.25669	
0.8423817863397548	0.7715649
0.07530647985989491	0.8294351
0.9083479276123759	0.8294351
e: 47
2/2 [==============================] - 0s 5ms/step


2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 3ms/step
47  of  60
108/108 [==============================] - 0s 2ms/step
error0 8.635012
108/108 [==============================] - 0s 2ms/step
[0.91012555 0.9938241  0.993831   ... 0.60977185 0.9948587  0.5843187 ]
pred_true: [[0.91012555]
 [0.9938241 ]
 [0.993831  ]
 ...
 [0.60977185]
 [0.9948587 ]
 [0.5843187 ]] 0.9349095154699358
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.3261804 ]
 [0.99251336]
 [0.28224266]
 ...
 [0.71266484]
 [0.98317474]
 [0.5127592 ]] 0.20957384705195564
108/108 [==============================] - 0s 2ms/step
pred_false2: [[2.3703642e-01]
 [4.4196866e-02]
 [4.3966800e-02]
 ...
 [4.2592084e-01]
 [4.8614487e-02]
 [9.5343697e-05]] 0.8499708114419148
8.635012	
0.9349095154699358	0.7833426
0.20957384705195564	0.6644561
0.8499708114419148	0.6644561
e: 48
2/2 [==============================] - 0s 602us/step


2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 5ms/step


2/2 [==============================] - 0s 16ms/step
48  of  60
108/108 [==============================] - 0s 3ms/step
error0 11.205931
108/108 [==============================] - 0s 3ms/step
[0.7169436  0.98508203 0.98508203 ... 0.55526483 0.98508203 0.57897013]
pred_true: [[0.7169436 ]
 [0.98508203]
 [0.98508203]
 ...
 [0.55526483]
 [0.98508203]
 [0.57897013]] 0.8528896672504378
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.99795073]
 [0.98507935]
 [0.9850049 ]
 ...
 [0.9609861 ]
 [0.98247844]
 [0.55325514]] 0.06654991243432574
108/108 [==============================] - 0s 3ms/step
pred_false2: [[1.9069773e-01]
 [3.0277260e-02]
 [3.0262487e-02]
 ...
 [4.2500353e-01]
 [3.0190621e-02]
 [1.2000349e-06]] 0.9328663164039697
11.205931	
0.8528896672504378	0.7535452
0.06654991243432574	0.8217974
0.9328663164039697	0.8217974
e: 49
2/2 [==============================] - 0s 16ms/step


2/2 [==============================] - 0s 16ms/step


2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 4ms/step
49  of  60
108/108 [==============================] - 0s 3ms/step
error0 10.26213
108/108 [==============================] - 0s 3ms/step
[0.7977694  0.9902757  0.990283   ... 0.52750486 0.99082714 0.5855195 ]
pred_true: [[0.7977694 ]
 [0.9902757 ]
 [0.990283  ]
 ...
 [0.52750486]
 [0.99082714]
 [0.5855195 ]] 0.8955049620548745
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.99718416]
 [0.9893465 ]
 [0.982124  ]
 ...
 [0.9913213 ]
 [0.98700184]
 [0.5131786 ]] 0.06275539988324577
108/108 [==============================] - 0s 2ms/step
pred_false2: [[1.09586984e-01]
 [3.58939543e-02]
 [3.59120369e-02]
 ...
 [3.52691263e-01]
 [3.78667973e-02]
 [4.08556133e-07]] 0.896964389959136
10.26213	
0.8955049620548745	0.76858234
0.06275539988324577	0.8148238
0.896964389959136	0.8148238
e: 50
2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 5ms/step


2/2 [==============================] - 0s 4ms/step
50  of  60
108/108 [==============================] - 0s 3ms/step
error0 9.028634
108/108 [==============================] - 0s 3ms/step
[0.945862   0.999132   0.9991417  ... 0.6500927  0.9994452  0.58940065]
pred_true: [[0.945862  ]
 [0.999132  ]
 [0.9991417 ]
 ...
 [0.6500927 ]
 [0.9994452 ]
 [0.58940065]] 0.9270286047869235
108/108 [==============================] - 0s 3ms/step
pred_false: [[0.9998669 ]
 [0.9990637 ]
 [0.9942413 ]
 ...
 [0.4415601 ]
 [0.56036574]
 [0.50867516]] 0.063922942206655
108/108 [==============================] - 0s 3ms/step
pred_false2: [[0.2840772 ]
 [0.06254735]
 [0.06302338]
 ...
 [0.44799402]
 [0.09194636]
 [0.00677911]] 0.7863397548161121
9.028634	
0.9270286047869235	0.7902773
0.063922942206655	0.8031029
0.7863397548161121	0.8031029
e: 51
2/2 [==============================] - 0s 10ms/step


2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 4ms/step
51  of  60
108/108 [==============================] - 0s 3ms/step
error0 8.623617
108/108 [==============================] - 0s 2ms/step
[0.89131284 0.9962753  0.99627614 ... 0.58019364 0.9964524  0.5852429 ]
pred_true: [[0.89131284]
 [0.9962753 ]
 [0.99627614]
 ...
 [0.58019364]
 [0.9964524 ]
 [0.5852429 ]] 0.8908347927612376
108/108 [==============================] - 0s 2ms/step
pred_false: [[0.9984621 ]
 [0.99603754]
 [0.98686826]
 ...
 [0.9960887 ]
 [0.3539986 ]
 [0.515028  ]] 0.15469935785172212


108/108 [==============================] - 0s 2ms/step
pred_false2: [[1.6981126e-01]
 [5.0179582e-02]
 [5.0066840e-02]
 ...
 [3.8567728e-01]
 [5.1351119e-02]
 [1.7478509e-07]] 0.9080560420315237
8.623617	
0.8908347927612376	0.7759764
0.15469935785172212	0.7377854
0.9080560420315237	0.7377854
e: 52
2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 4ms/step
52  of  60
108/108 [==============================] - 0s 3ms/step
error0 12.232361
108/108 [==============================] - 0s 3ms/step
[0.5391102 0.9888753 0.9888753 ... 0.5804157 0.9888753 0.5854966]
pred_true: [[0.5391102]
 [0.9888753]
 [0.9888753]
 ...
 [0.5804157]
 [0.9888753]
 [0.5854966]] 0.8744892002335085
108/108 [==============================] - 0s 3ms/step
pred_false: [[0.13581222]
 [0.98861843]
 [0.78883106]
 ...
 [0.38433945]
 [0.0893169 ]
 [0.5854966 ]] 0.2559836544074723
108/108 [==============================] - 0s 2ms/step
pred_false2: [[5.2291565e-02]
 [2.1612953e-02]
 [2.1545017e-02]
 ...
 [3.7514636e-01]
 [2.0754803e-02]
 [3.8613058e-07]] 0.8736135434909515
12.232361	
0.8744892002335085	0.75234807
0.2559836544074723	0.6447124
0.8736135434909515	0.6447124
e: 53
2/2 [==============================] - 0s 4ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 2ms/step
53  of  60
108/108 [==============================] - 0s 3ms/step
error0 10.680179
108/108 [==============================] - 0s 2ms/step
[0.9366098 0.9215282 0.9217485 ... 0.6153436 0.9309084 0.5967249]
pred_true: [[0.9366098]
 [0.9215282]
 [0.9217485]
 ...
 [0.6153436]
 [0.9309084]
 [0.5967249]] 0.9652656158785756
108/108 [==============================] - 0s 3ms/step
pred_false: [[0.99334973]
 [0.9404718 ]
 [0.8139528 ]
 ...
 [0.9855327 ]
 [0.9925529 ]
 [0.5967249 ]] 0.09544658493870403
108/108 [==============================] - 0s 3ms/step
pred_false2: [[2.1671653e-01]
 [5.9246574e-02]
 [5.9329201e-02]
 ...
 [3.9555928e-01]
 [6.5652572e-02]
 [1.1310501e-05]] 0.8952130764740222
10.680179	
0.9652656158785756	0.75554734
0.09544658493870403	0.7716105
0.8952130764740222	0.7716105
e: 54
2/2 [==============================] - 0s 16ms/step


2/2 [==============================] - 0s 7ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step
54  of  60
108/108 [==============================] - 0s 3ms/step
error0 7.4199443
108/108 [==============================] - 0s 3ms/step
[0.9012428  0.98878163 0.98879266 ... 0.6033401  0.98978776 0.5861286 ]
pred_true: [[0.9012428 ]
 [0.98878163]
 [0.98879266]
 ...
 [0.6033401 ]
 [0.98978776]
 [0.5861286 ]] 0.9784004670169294
108/108 [==============================] - 0s 3ms/step
pred_false: [[0.9961037 ]
 [0.9881222 ]
 [0.7759306 ]
 ...
 [0.9520955 ]
 [0.39228   ]
 [0.55460525]] 0.12463514302393462
108/108 [==============================] - 0s 2ms/step
pred_false2: [[2.2717389e-01]
 [7.3874556e-02]
 [7.3819019e-02]
 ...
 [4.1436347e-01]
 [7.8296795e-02]
 [4.0334780e-06]] 0.8739054290718039
7.4199443	
0.9784004670169294	0.78591573
0.12463514302393462	0.73097205
0.8739054290718039	0.73097205
e: 55
2/2 [==============================] - 0s 5ms/step


2/2 [==============================] - 0s 9ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 5ms/step
55  of  60
108/108 [==============================] - 0s 3ms/step
error0 7.758674
108/108 [==============================] - 0s 3ms/step
[0.72036755 0.97906315 0.97906315 ... 0.55443954 0.97906315 0.5805936 ]
pred_true: [[0.72036755]
 [0.97906315]
 [0.97906315]
 ...
 [0.55443954]
 [0.97906315]
 [0.5805936 ]] 0.9252772913018097
108/108 [==============================] - 0s 3ms/step
pred_false: [[0.87016547]
 [0.9630863 ]
 [0.5416807 ]
 ...
 [0.9651897 ]
 [0.9704896 ]
 [0.5560029 ]] 0.0837711617046118
108/108 [==============================] - 0s 3ms/step
pred_false2: [[9.4009422e-02]
 [5.9102252e-02]
 [5.9033979e-02]
 ...
 [3.7099549e-01]
 [5.8197644e-02]
 [7.0572219e-07]] 0.9071803852889667
7.758674	
0.9252772913018097	0.7606176
0.0837711617046118	0.75472677
0.9071803852889667	0.75472677
e: 56
2/2 [==============================] - 0s 2ms/step


2/2 [==============================] - 0s 17ms/step


2/2 [==============================] - 0s 16ms/step
56  of  60
108/108 [==============================] - 0s 3ms/step
error0 9.938732
108/108 [==============================] - 0s 3ms/step
[0.8109972  0.97385794 0.97385794 ... 0.55033034 0.97385794 0.580301  ]
pred_true: [[0.8109972 ]
 [0.97385794]
 [0.97385794]
 ...
 [0.55033034]
 [0.97385794]
 [0.580301  ]] 0.7904261529480444
108/108 [==============================] - 0s 3ms/step
pred_false: [[0.9313642 ]
 [0.9628122 ]
 [0.9386003 ]
 ...
 [0.38749012]
 [0.9781445 ]
 [0.580301  ]] 0.13572679509632224
108/108 [==============================] - 0s 3ms/step
pred_false2: [[1.0115758e-01]
 [3.7329588e-02]
 [3.7302244e-02]
 ...
 [3.7731051e-01]
 [3.6892638e-02]
 [2.7791214e-07]] 0.896964389959136
9.938732	
0.7904261529480444	0.75791293
0.13572679509632224	0.75955796
0.896964389959136	0.75955796
e: 57
2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 5ms/step
57  of  60
108/108 [==============================] - 0s 3ms/step
error0 17.226534
108/108 [==============================] - 0s 3ms/step
[0.679004   0.9918999  0.99191874 ... 0.5366509  0.9927206  0.59722054]
pred_true: [[0.679004  ]
 [0.9918999 ]
 [0.99191874]
 ...
 [0.5366509 ]
 [0.9927206 ]
 [0.59722054]] 0.9208990075890251
108/108 [==============================] - 0s 3ms/step
pred_false: [[0.9980152 ]
 [0.9925308 ]
 [0.99035853]
 ...
 [0.3723488 ]
 [0.9934904 ]
 [0.519991  ]] 0.05896088733216579
108/108 [==============================] - 0s 3ms/step
pred_false2: [[1.03750825e-01]
 [2.84758247e-02]
 [2.85362471e-02]
 ...
 [3.65023047e-01]
 [3.15407552e-02]
 [4.52677114e-06]] 0.8718622300058377
17.226534	
0.9208990075890251	0.7641693
0.05896088733216579	0.8245801
0.8718622300058377	0.8245801
e: 58
2/2 [==============================] - 0s 5ms/step


2/2 [==============================] - 0s 8ms/step


2/2 [==============================] - 0s 6ms/step


2/2 [==============================] - 0s 0s/step
58  of  60
108/108 [==============================] - 0s 3ms/step
error0 9.28514
108/108 [==============================] - 0s 3ms/step
[0.837288   0.98429203 0.98434883 ... 0.5947851  0.9878109  0.59279865]
pred_true: [[0.837288  ]
 [0.98429203]
 [0.98434883]
 ...
 [0.5947851 ]
 [0.9878109 ]
 [0.59279865]] 0.9906596614127262
108/108 [==============================] - 0s 3ms/step
pred_false: [[0.98081034]
 [0.9836187 ]
 [0.9846902 ]
 ...
 [0.9659157 ]
 [0.9906167 ]
 [0.74668527]] 0.07384705195563339
108/108 [==============================] - 0s 3ms/step
pred_false2: [[2.2726324e-01]
 [2.8078029e-02]
 [2.8124092e-02]
 ...
 [5.2331018e-01]
 [3.5054263e-02]
 [4.7859408e-05]] 0.854932866316404
9.28514	
0.9906596614127262	0.772729
0.07384705195563339	0.7865657
0.854932866316404	0.7865657
e: 59
2/2 [==============================] - 0s 5ms/step


2/2 [==============================] - 0s 17ms/step


2/2 [==============================] - 0s 0s/step


2/2 [==============================] - 0s 0s/step
59  of  60
108/108 [==============================] - 0s 3ms/step
error0 7.1042066
108/108 [==============================] - 0s 3ms/step
[0.9018431  0.99773216 0.9977366  ... 0.64083177 0.99847406 0.60806423]
pred_true: [[0.9018431 ]
 [0.99773216]
 [0.9977366 ]
 ...
 [0.64083177]
 [0.99847406]
 [0.60806423]] 0.9947460595446584
108/108 [==============================] - 0s 3ms/step
pred_false: [[0.99957216]
 [0.9976251 ]
 [0.9812229 ]
 ...
 [0.76701564]
 [0.9980048 ]
 [0.5994565 ]] 0.05808523058960887
108/108 [==============================] - 0s 3ms/step
pred_false2: [[2.3808357e-01]
 [5.5612650e-02]
 [5.5618040e-02]
 ...
 [4.3854406e-01]
 [7.8071505e-02]
 [1.2117104e-07]] 0.8461762988908348
7.1042066	
0.9947460595446584	0.79475236
0.05808523058960887	0.78061205
0.8461762988908348	0.78061205


In [12]:
from sklearn.metrics import confusion_matrix

noise = np.zeros((x_val.shape[0], z_input_size))
yhat = generator.predict([x_val,noise])
    
yhat=scaler.inverse_transform(yhat).flatten()
y_val0=scaler.inverse_transform(y_val).flatten()
print(y_val)
print(yhat)

file = open('prediction20.csv', 'w')
file.write('ground truth\tprediction\n')
for i in range(0,len(y_val)):
    file.write(str(y_val0[i])+"\t"+str(yhat[i])+"\n")
file.close()

print("RMSE")
error=tf.keras.metrics.mean_squared_error(
    y_val0, yhat
)
print(np.sqrt(error))

108/108 [==============================] - 0s 3ms/step
[[0.0141186 ]
 [0.        ]
 [0.        ]
 ...
 [0.07686223]
 [0.        ]
 [0.81869012]]
[  4.6227946    0.2351939    0.24211529 ...  11.4234915    0.36212564
 188.85933   ]
RMSE
7.1042066


In [13]:
noise = np.ones((x_val.shape[0], z_input_size))*tnoise
yhat = generator.predict([x_val,noise])
pred_false2=discriminator.predict([x_val, yhat])
acc_false2=len(pred_false2[pred_false2<0.5])/len(y_val)   
print("pred_false2:",pred_false2,acc_false2)


108/108 [==============================] - 0s 3ms/step
pred_false2: [[0.28426376]
 [0.7378714 ]
 [0.7306341 ]
 ...
 [0.44202676]
 [0.69200265]
 [0.60806423]] 0.1640396964389959


In [14]:
    noise = np.ones((x_val.shape[0], z_input_size))*tnoise
    yhat = generator.predict([x_val,noise])
    pred_false2=discriminator.predict([x_val, yhat+tnoise])
    acc_false2=len(pred_false2[pred_false2<0.5])/len(y_val)   
    print("pred_false2:",pred_false2,acc_false2)


108/108 [==============================] - 0s 3ms/step
pred_false2: [[2.3561457e-01]
 [4.1011140e-02]
 [4.1086741e-02]
 ...
 [4.3993732e-01]
 [5.9774566e-02]
 [6.8763246e-17]] 0.8966725043782837
